In [1]:
import numpy as np ## importing numpy , import is key word , as is alias , np is alias
print(np.__version__)

2.3.1


In [17]:
lis = [1,2,3,4,5]
print(lis)
print("type of list :-",type(lst))
      

[1, 2, 3, 4, 5]
type of list :- <class 'list'>


In [18]:
arr = np . array(lst)
print(arr)
print("type of array:-",type(arr))

[1 2 3 4 5 6 7 8 9]
type of array:- <class 'numpy.ndarray'>


In [4]:
lst = list(range(1,10))
print(type(lst))
arr = np.array(lst)
arr

<class 'list'>


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr = np. arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
arr =np.arange(1,31)

In [24]:
arr.reshape(5,6)
arr

ValueError: cannot reshape array of size 9 into shape (5,6)

In [26]:
arr=np.random.randint(1,5,9)
arr

array([3, 1, 1, 2, 1, 3, 4, 2, 3], dtype=int32)

In [27]:
arr=np.random.randint(1,5,(5,2))
arr

array([[2, 4],
       [2, 3],
       [3, 4],
       [3, 1],
       [3, 2]], dtype=int32)

In [29]:
np.random.random((5,2))


array([[0.36876875, 0.77189687],
       [0.80715172, 0.39786746],
       [0.55537884, 0.87459229],
       [0.82883999, 0.42033897],
       [0.93194743, 0.57029194]])

In [67]:
np.arange(60).reshape(12,5)



array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [31]:
print("array shape:-",arr.shape)
print("size shape:-",arr.size)
print("number of dim:-",arr.ndim)
print("dtype of array:-",arr.dtype)

array shape:- (5, 2)
size shape:- 10
number of dim:- 2
dtype of array:- int32


In [40]:
arr.flatten()

array([2, 4, 2, 3, 3, 4, 3, 1, 3, 2], dtype=int32)

In [ ]:
arr.ravel()


array([2, 4, 2, 3, 3, 4, 3, 1, 3, 2], dtype=int32)

In [34]:
print("array shape:-",arr.shape)
print("size shape:-",arr.size)
print("number of dim:-",arr.ndim)
print("dtype of array:-",arr.dtype)

array shape:- (5, 2)
size shape:- 10
number of dim:- 2
dtype of array:- int32


In [38]:
arr.T

array([2, 4, 2, 3, 3, 4, 3, 1, 3, 2], dtype=int32)

In [44]:
arr[0]


np.int32(2)

In [45]:
arr[0:2]

array([2, 4], dtype=int32)

In [50]:
arr[0:2][0:2]

array([2, 4], dtype=int32)

In [64]:
arr[arr==59]=100
arr

array([2, 4, 2, 3, 3, 4, 3, 1, 3, 2], dtype=int32)

In [ ]:
# min,max,mine


In [73]:
arr = np.array(np.arange(225).reshape(5,15,3))
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [74]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [75]:
print("array shape:-",arr.shape)
print("size shape:-",arr.size)
print("number of dim:-",arr.ndim)
print("dtype of array:-",arr.dtype)

array shape:- (5, 15, 3)
size shape:- 225
number of dim:- 3
dtype of array:- int64


In [76]:
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [77]:
arr[0][0][0]

np.int64(0)

In [78]:
arr[0:2,1:3,1:3]

array([[[ 4,  5],
        [ 7,  8]],

       [[49, 50],
        [52, 53]]])

In [79]:
arr[0]
arr[1]


array([[45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89]])

In [80]:
arr[0:5,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [81]:
arr[0:6,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [84]:
arr = np.array([5,1,9,3])
print(np.min(arr))

1


In [85]:
arr = np.array([5,1,9,3])
print(np.max(arr))

9


In [87]:
arr = np.array([5,1,9,3])
print(np.mean(arr))

4.5
